short_name = "tdtstack"
name = "Techno Digital Twin Stack"
major = 1
minor = 0
patch = 0
status = "alpha"
module_config = ""
company = "Technostacks Infotech Private Limited"
website = "https://technostacks.com"
docs = "https://technostacks.com/tdt-stack/docs"
support = "https://technostacks.com/support"
