#!/usr/bin/env python

Import("env")
Import("env_modules")

env_dt = env_modules.Clone()

# Add source files for digital_twin module
env_dt.add_source_files(env.modules_sources, "*.cpp")
env_dt.add_source_files(env.modules_sources, "core/*.cpp")
