#!/usr/bin/env python

Import("env")
Import("env_modules")

env_dt = env_modules.Clone()

# Godot source files
module_obj = []

env_dt.add_source_files(module_obj, "*.cpp")
env_dt.add_source_files(module_obj, "core/*.cpp")

env.modules_sources += module_obj

# Needed to force rebuild the module files when the thirdparty library is updated.
env.Depends(module_obj, thirdparty_obj)
